Bump io.lettuce:lettuce-core from 6.7.1.RELEASE to 6.8.0.RELEASE (#12)
Bumps [io.lettuce:lettuce-core](https://github.com/redis/lettuce) from
6.7.1.RELEASE to 6.8.0.RELEASE.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/redis/lettuce/releases">io.lettuce:lettuce-core's
releases</a>.</em></p>
<blockquote>
<h2>6.8.0.RELEASE</h2>
<p>The Lettuce team is pleased to announce the Lettuce 6.8.0 minor
release!</p>
<p>This release provides support for the newly introduced <a
href="https://redis.github.io/lettuce/user-guide/redis-search/">Redis
Query Engine support</a> which was is part of Redis 8.0 and previously -
as part of RedisStack. The new operators (<code>DIFF</code>,
<code>DIFF1</code>, <code>ANDOR</code> and <code>ONE</code>) for the
<code>BITOP</code> command are also available. The team has worked on
extending the contract of the <code>XADD</code> and <code>XTRIM </code>
commands to support trimming policy, and also introduced the new
<code>XDELEX</code> and <code>XACKDEL</code> commands.</p>
<p>Lettuce 6.8.0 supports Redis 2.6+ up to Redis 8.x. In terms of Java
runtime, Lettuce requires at least Java 8 and
works with Java 24. The driver is tested against Redis 8.2, Redis 8.0,
Redis 7.4 and Redis 7.2.</p>
<p>Find the full changelog at the end of this document.
Thanks to all contributors who made Lettuce 6.8.0.RELEASE possible.</p>
<p>📗 Links
Reference documentation: <a
href="https://lettuce.io/core/6.8.0.RELEASE/reference/">https://lettuce.io/core/6.8.0.RELEASE/reference/</a>
Javadoc: <a
href="https://lettuce.io/core/6.8.0.RELEASE/api/">https://lettuce.io/core/6.8.0.RELEASE/api/</a></p>
<p>⭐ New Features
Introduce RediSearch by <a
href="https://github.com/tishun"><code>@​tishun</code></a> in <a
href="https://redirect.github.com/redis/lettuce/pull/3375">redis/lettuce#3375</a>
Add support for new operations of BITOP command in Redis Community
Edition 8.2 by <a
href="https://github.com/atakavci"><code>@​atakavci</code></a> in <a
href="https://redirect.github.com/redis/lettuce/pull/3334">redis/lettuce#3334</a>
Add support for 8.2 stream commands by <a
href="https://github.com/uglide"><code>@​uglide</code></a> in <a
href="https://redirect.github.com/redis/lettuce/pull/3374">redis/lettuce#3374</a></p>
<p>🐞 Bug Fixes
NoClassDefFoundError in Lettuce 6.7.0 <a
href="https://redirect.github.com/redis/lettuce/issues/3317">#3317</a>
by <a href="https://github.com/tishun"><code>@​tishun</code></a> in <a
href="https://redirect.github.com/redis/lettuce/pull/3318">redis/lettuce#3318</a></p>
<p>💡 Other
The instance of the <code>ObjectMapper</code> can now be reused in the
<code>DefaultJsonParser</code> by <a
href="https://github.com/thachlp"><code>@​thachlp</code></a> in <a
href="https://redirect.github.com/redis/lettuce/pull/3372">redis/lettuce#3372</a>
Added basic connection interruption tests by <a
href="https://github.com/uglide"><code>@​uglide</code></a> in <a
href="https://redirect.github.com/redis/lettuce/pull/3292">redis/lettuce#3292</a>
DOC-4758 async JSON doc examples by <a
href="https://github.com/andy-stark-redis"><code>@​andy-stark-redis</code></a>
in <a
href="https://redirect.github.com/redis/lettuce/pull/3335">redis/lettuce#3335</a>
Fixed SocketOptions.Builder validation messages by <a
href="https://github.com/hubertchylik"><code>@​hubertchylik</code></a>
in <a
href="https://redirect.github.com/redis/lettuce/pull/3366">redis/lettuce#3366</a>
Refactor tests for clarity and maintainability by <a
href="https://github.com/Rian-Ismael"><code>@​Rian-Ismael</code></a> in
<a
href="https://redirect.github.com/redis/lettuce/pull/3363">redis/lettuce#3363</a>
Provide support for the SVS-VMANA index (<a
href="https://redirect.github.com/redis/lettuce/issues/3385">#3385</a>)
by <a href="https://github.com/tishun"><code>@​tishun</code></a> in <a
href="https://redirect.github.com/redis/lettuce/pull/3386">redis/lettuce#3386</a></p>
<p>❤️ New Contributors## New Contributors</p>
<ul>
<li><a
href="https://github.com/hubertchylik"><code>@​hubertchylik</code></a>
made their first contribution in <a
href="https://redirect.github.com/redis/lettuce/pull/3366">redis/lettuce#3366</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/redis/lettuce/compare/6.7.0.RELEASE...6.8.0.RELEASE">https://github.com/redis/lettuce/compare/6.7.0.RELEASE...6.8.0.RELEASE</a></p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/redis/lettuce/blob/main/RELEASE-NOTES.md">io.lettuce:lettuce-core's
changelog</a>.</em></p>
<blockquote>
<h1>Lettuce 6.8.0 RELEASE NOTES</h1>
<p>The Redis team is delighted to announce the release of Lettuce
6.8.0</p>
<p>Lettuce 6 supports Redis 2.6+ up to Redis 7.x. In terms of Java
runtime, Lettuce requires
at least Java 8 and works with Java 21.</p>
<p>Thanks to all contributors who made Lettuce 6.8.0 possible.</p>
<p>If you need any support, meet Lettuce at</p>
<ul>
<li>GitHub Discussions: <a
href="https://github.com/lettuce-io/lettuce-core/discussions">https://github.com/lettuce-io/lettuce-core/discussions</a></li>
<li>Stack Overflow (Questions): <a
href="https://stackoverflow.com/questions/tagged/lettuce">https://stackoverflow.com/questions/tagged/lettuce</a></li>
<li>Join the chat at <a
href="https://discord.gg/redis">https://discord.gg/redis</a> and look
for the &quot;Help:Tools Lettuce&quot; channel</li>
<li>GitHub Issues (Bug reports, feature requests): <a
href="https://github.com/lettuce-io/lettuce-core/issues">https://github.com/lettuce-io/lettuce-core/issues</a></li>
<li>Documentation: <a
href="https://lettuce.io/core/6.8.0.RELEASE/reference/">https://lettuce.io/core/6.8.0.RELEASE/reference/</a></li>
<li>Javadoc: <a
href="https://lettuce.io/core/6.8.0.RELEASE/api/">https://lettuce.io/core/6.8.0.RELEASE/api/</a></li>
</ul>
<h2>Commands</h2>
<ul>
<li>Introduce RediSearch by <a
href="https://github.com/tishun"><code>@​tishun</code></a> in <a
href="https://redirect.github.com/redis/lettuce/pull/3375">redis/lettuce#3375</a></li>
<li>Add support for new operations of BITOP command in Redis Community
Edition 8.2 by <a
href="https://github.com/atakavci"><code>@​atakavci</code></a> in <a
href="https://redirect.github.com/redis/lettuce/pull/3334">redis/lettuce#3334</a></li>
<li>Add support for 8.2 stream commands by <a
href="https://github.com/uglide"><code>@​uglide</code></a> in <a
href="https://redirect.github.com/redis/lettuce/pull/3374">redis/lettuce#3374</a></li>
</ul>
<h2>Enhancements</h2>
<ul>
<li>N/A</li>
</ul>
<h2>Fixes</h2>
<ul>
<li>NoClassDefFoundError in Lettuce 6.7.0 <a
href="https://redirect.github.com/redis/lettuce/issues/3317">#3317</a>
by <a href="https://github.com/tishun"><code>@​tishun</code></a> in <a
href="https://redirect.github.com/redis/lettuce/pull/3318">redis/lettuce#3318</a></li>
</ul>
<h2>Other</h2>
<ul>
<li>The instance of the <code>ObjectMapper</code> can now be reused in
the <code>DefaultJsonParser</code> by <a
href="https://github.com/thachlp"><code>@​thachlp</code></a> in <a
href="https://redirect.github.com/redis/lettuce/pull/3372">redis/lettuce#3372</a></li>
<li>Added basic connection interruption tests by <a
href="https://github.com/uglide"><code>@​uglide</code></a> in <a
href="https://redirect.github.com/redis/lettuce/pull/3292">redis/lettuce#3292</a></li>
<li>DOC-4758 async JSON doc examples by <a
href="https://github.com/andy-stark-redis"><code>@​andy-stark-redis</code></a>
in <a
href="https://redirect.github.com/redis/lettuce/pull/3335">redis/lettuce#3335</a></li>
<li>Fixed SocketOptions.Builder validation messages by <a
href="https://github.com/hubertchylik"><code>@​hubertchylik</code></a>
in <a
href="https://redirect.github.com/redis/lettuce/pull/3366">redis/lettuce#3366</a></li>
<li>Refactor tests for clarity and maintainability by <a
href="https://github.com/Rian-Ismael"><code>@​Rian-Ismael</code></a> in
<a
href="https://redirect.github.com/redis/lettuce/pull/3363">redis/lettuce#3363</a></li>
<li>Provide support for the SVS-VMANA index (<a
href="https://redirect.github.com/redis/lettuce/issues/3385">#3385</a>)
by <a href="https://github.com/tishun"><code>@​tishun</code></a> in <a
href="https://redirect.github.com/redis/lettuce/pull/3386">redis/lettuce#3386</a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/redis/lettuce/commit/8e6e63d1944ec452cbefad973b897e44d5f1bf41"><code>8e6e63d</code></a>
Release 6.8.0.RELEASE (<a
href="https://redirect.github.com/redis/lettuce/issues/3388">#3388</a>)</li>
<li><a
href="https://github.com/redis/lettuce/commit/5794560a91ceabeb2491e3575245fb627d126e2c"><code>5794560</code></a>
reuse-objectmapper-defaultjsonparser (<a
href="https://redirect.github.com/redis/lettuce/issues/3372">#3372</a>)</li>
<li><a
href="https://github.com/redis/lettuce/commit/b789b62c82b1b6d72888821ada0ab8353d81b2a4"><code>b789b62</code></a>
Provide support for the SVS-VMANA index (<a
href="https://redirect.github.com/redis/lettuce/issues/3385">#3385</a>)
(<a
href="https://redirect.github.com/redis/lettuce/issues/3386">#3386</a>)</li>
<li><a
href="https://github.com/redis/lettuce/commit/6567f2d5e56e04524f57e20b7a054cfe92c2aab7"><code>6567f2d</code></a>
Introduce RediSearch (<a
href="https://redirect.github.com/redis/lettuce/issues/3375">#3375</a>)</li>
<li><a
href="https://github.com/redis/lettuce/commit/6e7bb1047cc6d775b9973c64aa1908367c63f304"><code>6e7bb10</code></a>
Bumping to 8.2-rc2-pre (<a
href="https://redirect.github.com/redis/lettuce/issues/3376">#3376</a>)</li>
<li><a
href="https://github.com/redis/lettuce/commit/2a7d2a40de32f29b73fa5354651f723b81c7631c"><code>2a7d2a4</code></a>
Refactor tests for clarity and maintainability (<a
href="https://redirect.github.com/redis/lettuce/issues/3363">#3363</a>)</li>
<li><a
href="https://github.com/redis/lettuce/commit/85b65f21204807b700a436ba136869c5f46bed7f"><code>85b65f2</code></a>
Fixed SocketOptions.Builder validation messages (<a
href="https://redirect.github.com/redis/lettuce/issues/3366">#3366</a>)</li>
<li><a
href="https://github.com/redis/lettuce/commit/2e4300fe6a8fe323e23f7ff482a9c5b5f72b81ac"><code>2e4300f</code></a>
Add support for 8.2 stream commands (<a
href="https://redirect.github.com/redis/lettuce/issues/3374">#3374</a>)</li>
<li><a
href="https://github.com/redis/lettuce/commit/371beb09547e85f8e981c1c4ebb70c3e3179d3d2"><code>371beb0</code></a>
DOC-4758 async JSON doc examples (<a
href="https://redirect.github.com/redis/lettuce/issues/3335">#3335</a>)</li>
<li><a
href="https://github.com/redis/lettuce/commit/d5eb193cd85965410c1c0b13f4c4894cf748db45"><code>d5eb193</code></a>
Migrate publishing to Maven Central Portal (<a
href="https://redirect.github.com/redis/lettuce/issues/3348">#3348</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/redis/lettuce/compare/6.7.1.RELEASE...6.8.0.RELEASE">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=io.lettuce:lettuce-core&package-manager=gradle&previous-version=6.7.1.RELEASE&new-version=6.8.0.RELEASE)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: W. Duncan Fraser <duncan@relianteng.io>